### ISSUE TITLE
Release tags incompatible with oclif readme

### ISSUE THREAD

**Issue by ben-impart** [oclif/plugin-autocomplete#422] opened 2023-02-06 20:46 UTC
I just noticed that when running `oclif readme` that the autocomplete command is added to the `README.md` with a broken link. eg:
`_See code: [@oclif/plugin-autocomplete](https://github.com/oclif/plugin-autocomplete/blob/v1.4.5/src/commands/autocomplete/index.ts)_`

The template to generate that link is in the `oclif` package and expects the release tag to be prefixed with `v`:
https://github.com/oclif/oclif/blob/d8352ffe6bfcdfca7c0021ef53b8a8e38477cae7/src/commands/readme.ts#L203

Releases for `plugin-autocomplete` stopped being prefixed with `v` early last year:
https://github.com/oclif/plugin-autocomplete/releases?page=2

Unclear whether the template should be updated or releases prefixed again but wanted to point it out.

**Comment by JLeander23** [comment] 2023-03-13 19:38
> I just noticed that when running `oclif readme` that the autocomplete command is added to the `README.md` with a broken link. eg: `_See code: [@oclif/plugin-autocomplete](https://github.com/oclif/plugin-autocomplete/blob/v1.4.5/src/commands/autocomplete/index.ts)_`
> 
> The template to generate that link is in the `oclif` package and expects the release tag to be prefixed with `v`: https://github.com/oclif/oclif/blob/d8352ffe6bfcdfca7c0021ef53b8a8e38477cae7/src/commands/readme.ts#L203
> 
> Releases for `plugin-autocomplete` stopped being prefixed with `v` early last year: https://github.com/oclif/plugin-autocomplete/releases?page=2
> 
> Unclear whether the template should be updated or releases prefixed again but wanted to point it out.

**Comment by mdonnalley** [comment] 2024-03-07 17:48
I believe this is a duplicate of https://github.com/oclif/oclif/issues/927 which was fixed by https://github.com/oclif/oclif/pull/1191

Closing this but please feel free to open a new issue in the [oclif/oclif](https://github.com/oclif/oclif) repo if it's still an issue for you.

**Closed by mdonnalley** 2024-03-07 17:48 UTC
